### ISSUE TITLE
FastBoot compatability

### ISSUE THREAD

**Issue by revanar** [migeorge/ember-cli-flexibility#2]
FastBoot currently fails to build with this addon.  Is there any recommended pattern for guarding this, or a plan for adding FastBoot support?

Thanks!

-Matt

**Comment by migeorge** [comment]
Thanks for submitting this issue!

I haven't had a need for FastBoot yet so it is untested for this addon. I'll take a look at the requirements and see if I can fix it up within the next few days.

**Comment by migeorge** [comment]
v2.0.2 is now live
